name: Hello Word

on:
  push:
    branches: [main]

jobs:
    greets:
        runs-on: ubuntu-latest
        steps:
            - name: say hello
              run: echo "hello"

            - name: say hello to every everyone
              run: echo "hello evryone"

      details:
          runs-on: ubuntu-latest
          steps:
              - name: show what is the version of python,docker ,etc
                run: docker --version && python --version


          
